DROP TABLE PEDIDO_PRODUCTO;
DROP TABLE PRODUCTO;
DROP TABLE CATEGORIA;
DROP TABLE PEDIDO;
DROP TABLE USUARIO;
DROP TABLE PAGO;
DROP TABLE PERFIL;

CREATE TABLE Perfil(
    idPerfil NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombrePerfil VARCHAR2(13) CHECK 
        (nombrePerfil IN ('CLIENTE','SECRETARIO','ADMINISTRADOR')) NOT NULL,
    descripcion VARCHAR2(300) NOT NULL,
    PRIMARY KEY (idPerfil)
);

CREATE TABLE Pago(
    idPago NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tipoPago VARCHAR2(15) CHECK 
        (tipoPago IN ('TARJETA','CONTRAREEMBOLSO')) NOT NULL,
    descripcion VARCHAR2(300) NOT NULL,
    PRIMARY KEY (idPago)
);

CREATE TABLE Usuario(
    idUsuario NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(20) NOT NULL,
    primerApellido VARCHAR2(20) NOT NULL,
    segundoApellido VARCHAR2(20) NOT NULL,
    email VARCHAR2(300) NOT NULL,
    contraseña VARCHAR2(150) NOT NULL,
    idPerfil NUMBER NOT NULL,
    idPago NUMBER,
    PRIMARY KEY (idUsuario)
);

CREATE TABLE Pedido(
    idPedido NUMBER GENERATED BY DEFAULT AS IDENTITY,
    precioTotal NUMBER(5) NOT NULL,
    realizado NUMBER(1,0) DEFAULT 0 NOT NULL,
    idUsuario NUMBER,
    idPago NUMBER,
    PRIMARY KEY (idPedido)
);

CREATE TABLE Categoria(
    idCategoria NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tipoCategoria VARCHAR2(19) CHECK
        (tipoCategoria IN ('BEBIDAS ALCOHÓLICAS', 'FRUTAS', 'VERDURAS', 
        'HUEVOS Y LÁCTEOS', 'CAFÉ E INFUSIONES', 'POSTRES Y CEREALES')) NOT NULL,
    descripcion VARCHAR2(300) NOT NULL,
    PRIMARY KEY (idCategoria)
);

CREATE TABLE Producto(
    idProducto NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(60) NOT NULL,
    precio NUMBER(3) NOT NULL,
    descrpcion VARCHAR2(500) NOT NULL,
    cantidad NUMBER(4) NOT NULL,
    foto VARCHAR2(200) NOT NULL,
    idCategoria NUMBER NOT NULL,
    PRIMARY KEY (idProducto)
);

CREATE TABLE Pedido_Producto(
    idPedido NUMBER GENERATED BY DEFAULT AS IDENTITY,
    idProducto NUMBER,
    cantidad NUMBER(4),
    PRIMARY KEY (idPedido, idProducto)
);

/*CLAVES FORÁNEAS*/

ALTER TABLE Pedido_Producto ADD(
    CONSTRAINT FK_Pedido__Pedido_Producto
        FOREIGN KEY (idPedido) REFERENCES Pedido(idPedido),
    CONSTRAINT FK_Producto__Pedido_Producto
        FOREIGN KEY (idProducto) REFERENCES Producto(idProducto)
);

ALTER TABLE Producto ADD(
    CONSTRAINT FK_Categoria_Producto
        FOREIGN KEY (idCategoria) REFERENCES Categoria(idCategoria)
);

ALTER TABLE Pedido ADD(
    CONSTRAINT FK_Usuario_Pedido
        FOREIGN KEY (idUsuario) REFERENCES Usuario(idUsuario),
    CONSTRAINT FK_Pago_Pedido
        FOREIGN KEY (idPago) REFERENCES Pago(idPago)
);

ALTER TABLE Usuario ADD(
    CONSTRAINT FK_Perfil_Usuario
        FOREIGN KEY (idPerfil) REFERENCES Perfil(idPerfil),
    CONSTRAINT FK_Pago_Usuario
        FOREIGN KEY (idPago) REFERENCES Pago(idPago)
);