openapi: 3.0.0
info:
  title: API en desarrollo de Eccomerce
  description: API en desarrollo para una tienda que vende productos ecológicos.
  version: "0.1"
servers:
  - url: http://127.0.0.1:8090/
paths: